CREATE TABLE "BSMART_DATA"."STP_PAYMENT_ITEMS"(
	"TREEID" NUMBER,
	"CONTRACT_ITEM_ID" NVARCHAR2(4), 
	"PAYMENT_CERT_NO" NUMBER,
	"PAYMENT_STATUS" VARCHAR2(128 BYTE),
	CONSTRAINT "STP_TREEID_PK" PRIMARY KEY("TREEID")
	);